//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.06 at 02:30:00 PM EST 
//


package config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Tag"/>
 *         &lt;element ref="{}OriginalDataFilePath"/>
 *         &lt;element ref="{}ExperimentReference"/>
 *         &lt;element ref="{}ConfigurationPath"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tag",
    "originalDataFilePath",
    "experimentReference",
    "configurationPath"
})
@XmlRootElement(name = "AdditionalDataSet")
public class AdditionalDataSet {

    @XmlElement(name = "Tag", required = true)
    protected String tag;
    @XmlElement(name = "OriginalDataFilePath", required = true)
    protected String originalDataFilePath;
    @XmlElement(name = "ExperimentReference", required = true)
    protected ExperimentReference experimentReference;
    @XmlElement(name = "ConfigurationPath", required = true)
    protected String configurationPath;

    /**
     * Gets the value of the tag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTag() {
        return tag;
    }

    /**
     * Sets the value of the tag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTag(String value) {
        this.tag = value;
    }

    /**
     * Gets the value of the originalDataFilePath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalDataFilePath() {
        return originalDataFilePath;
    }

    /**
     * Sets the value of the originalDataFilePath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalDataFilePath(String value) {
        this.originalDataFilePath = value;
    }

    /**
     * Gets the value of the experimentReference property.
     * 
     * @return
     *     possible object is
     *     {@link ExperimentReference }
     *     
     */
    public ExperimentReference getExperimentReference() {
        return experimentReference;
    }

    /**
     * Sets the value of the experimentReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExperimentReference }
     *     
     */
    public void setExperimentReference(ExperimentReference value) {
        this.experimentReference = value;
    }

    /**
     * Gets the value of the configurationPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfigurationPath() {
        return configurationPath;
    }

    /**
     * Sets the value of the configurationPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfigurationPath(String value) {
        this.configurationPath = value;
    }

}
