//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.06 at 02:30:00 PM EST 
//


package config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}OriginalDataFilePath"/>
 *         &lt;element ref="{}CachedDataFilePath" minOccurs="0"/>
 *         &lt;element ref="{}ExperimentReference" minOccurs="0"/>
 *         &lt;element ref="{}LeftBarcode" minOccurs="0"/>
 *         &lt;element ref="{}RightBarcode" minOccurs="0"/>
 *         &lt;element ref="{}Filter" minOccurs="0"/>
 *         &lt;element ref="{}TotalLineCount"/>
 *         &lt;element ref="{}TotalReadCount"/>
 *         &lt;element ref="{}TotalBarcodeMatchedReadCount"/>
 *         &lt;element ref="{}ValidReadCount"/>
 *         &lt;element ref="{}Kmax" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "originalDataFilePath",
    "cachedDataFilePath",
    "experimentReference",
    "leftBarcode",
    "rightBarcode",
    "filter",
    "totalLineCount",
    "totalReadCount",
    "totalBarcodeMatchedReadCount",
    "validReadCount",
    "kmax"
})
@XmlRootElement(name = "InputDataSetStats")
public class InputDataSetStats {

    @XmlElement(name = "OriginalDataFilePath", required = true)
    protected String originalDataFilePath;
    @XmlElement(name = "CachedDataFilePath")
    protected String cachedDataFilePath;
    @XmlElement(name = "ExperimentReference")
    protected ExperimentReference experimentReference;
    @XmlElement(name = "LeftBarcode")
    protected String leftBarcode;
    @XmlElement(name = "RightBarcode")
    protected String rightBarcode;
    @XmlElement(name = "Filter", defaultValue = "")
    protected String filter;
    @XmlElement(name = "TotalLineCount")
    protected long totalLineCount;
    @XmlElement(name = "TotalReadCount")
    protected long totalReadCount;
    @XmlElement(name = "TotalBarcodeMatchedReadCount")
    protected long totalBarcodeMatchedReadCount;
    @XmlElement(name = "ValidReadCount")
    protected long validReadCount;
    @XmlElement(name = "Kmax")
    protected Integer kmax;
    @XmlAttribute(required = true)
    protected String id;

    /**
     * Gets the value of the originalDataFilePath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalDataFilePath() {
        return originalDataFilePath;
    }

    /**
     * Sets the value of the originalDataFilePath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalDataFilePath(String value) {
        this.originalDataFilePath = value;
    }

    /**
     * Gets the value of the cachedDataFilePath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCachedDataFilePath() {
        return cachedDataFilePath;
    }

    /**
     * Sets the value of the cachedDataFilePath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCachedDataFilePath(String value) {
        this.cachedDataFilePath = value;
    }

    /**
     * Gets the value of the experimentReference property.
     * 
     * @return
     *     possible object is
     *     {@link ExperimentReference }
     *     
     */
    public ExperimentReference getExperimentReference() {
        return experimentReference;
    }

    /**
     * Sets the value of the experimentReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExperimentReference }
     *     
     */
    public void setExperimentReference(ExperimentReference value) {
        this.experimentReference = value;
    }

    /**
     * Gets the value of the leftBarcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLeftBarcode() {
        return leftBarcode;
    }

    /**
     * Sets the value of the leftBarcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLeftBarcode(String value) {
        this.leftBarcode = value;
    }

    /**
     * Gets the value of the rightBarcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRightBarcode() {
        return rightBarcode;
    }

    /**
     * Sets the value of the rightBarcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRightBarcode(String value) {
        this.rightBarcode = value;
    }

    /**
     * Gets the value of the filter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFilter() {
        return filter;
    }

    /**
     * Sets the value of the filter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFilter(String value) {
        this.filter = value;
    }

    /**
     * Gets the value of the totalLineCount property.
     * 
     */
    public long getTotalLineCount() {
        return totalLineCount;
    }

    /**
     * Sets the value of the totalLineCount property.
     * 
     */
    public void setTotalLineCount(long value) {
        this.totalLineCount = value;
    }

    /**
     * Gets the value of the totalReadCount property.
     * 
     */
    public long getTotalReadCount() {
        return totalReadCount;
    }

    /**
     * Sets the value of the totalReadCount property.
     * 
     */
    public void setTotalReadCount(long value) {
        this.totalReadCount = value;
    }

    /**
     * Gets the value of the totalBarcodeMatchedReadCount property.
     * 
     */
    public long getTotalBarcodeMatchedReadCount() {
        return totalBarcodeMatchedReadCount;
    }

    /**
     * Sets the value of the totalBarcodeMatchedReadCount property.
     * 
     */
    public void setTotalBarcodeMatchedReadCount(long value) {
        this.totalBarcodeMatchedReadCount = value;
    }

    /**
     * Gets the value of the validReadCount property.
     * 
     */
    public long getValidReadCount() {
        return validReadCount;
    }

    /**
     * Sets the value of the validReadCount property.
     * 
     */
    public void setValidReadCount(long value) {
        this.validReadCount = value;
    }

    /**
     * Gets the value of the kmax property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getKmax() {
        return kmax;
    }

    /**
     * Sets the value of the kmax property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setKmax(Integer value) {
        this.kmax = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
