//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.06 at 02:30:00 PM EST 
//


package config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}ExperimentReference"/>
 *         &lt;element ref="{}Filter" minOccurs="0"/>
 *         &lt;element ref="{}Length"/>
 *         &lt;element ref="{}Offset"/>
 *         &lt;element ref="{}LowestCount" minOccurs="0"/>
 *         &lt;element ref="{}HighestCount" minOccurs="0"/>
 *         &lt;element ref="{}ValidReadCount"/>
 *         &lt;element ref="{}KmerCountStatsTablePath"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "experimentReference",
    "filter",
    "length",
    "offset",
    "lowestCount",
    "highestCount",
    "validReadCount",
    "kmerCountStatsTablePath"
})
@XmlRootElement(name = "KmerCountStats")
public class KmerCountStats {

    @XmlElement(name = "ExperimentReference", required = true)
    protected ExperimentReference experimentReference;
    @XmlElement(name = "Filter", defaultValue = "")
    protected String filter;
    @XmlElement(name = "Length")
    protected int length;
    @XmlElement(name = "Offset", defaultValue = "-1")
    protected int offset;
    @XmlElement(name = "LowestCount")
    protected Long lowestCount;
    @XmlElement(name = "HighestCount")
    protected Long highestCount;
    @XmlElement(name = "ValidReadCount")
    protected long validReadCount;
    @XmlElement(name = "KmerCountStatsTablePath", required = true)
    protected String kmerCountStatsTablePath;
    @XmlAttribute(required = true)
    protected String id;

    /**
     * Gets the value of the experimentReference property.
     * 
     * @return
     *     possible object is
     *     {@link ExperimentReference }
     *     
     */
    public ExperimentReference getExperimentReference() {
        return experimentReference;
    }

    /**
     * Sets the value of the experimentReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExperimentReference }
     *     
     */
    public void setExperimentReference(ExperimentReference value) {
        this.experimentReference = value;
    }

    /**
     * Gets the value of the filter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFilter() {
        return filter;
    }

    /**
     * Sets the value of the filter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFilter(String value) {
        this.filter = value;
    }

    /**
     * Gets the value of the length property.
     * 
     */
    public int getLength() {
        return length;
    }

    /**
     * Sets the value of the length property.
     * 
     */
    public void setLength(int value) {
        this.length = value;
    }

    /**
     * Gets the value of the offset property.
     * 
     */
    public int getOffset() {
        return offset;
    }

    /**
     * Sets the value of the offset property.
     * 
     */
    public void setOffset(int value) {
        this.offset = value;
    }

    /**
     * Gets the value of the lowestCount property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getLowestCount() {
        return lowestCount;
    }

    /**
     * Sets the value of the lowestCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setLowestCount(Long value) {
        this.lowestCount = value;
    }

    /**
     * Gets the value of the highestCount property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getHighestCount() {
        return highestCount;
    }

    /**
     * Sets the value of the highestCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHighestCount(Long value) {
        this.highestCount = value;
    }

    /**
     * Gets the value of the validReadCount property.
     * 
     */
    public long getValidReadCount() {
        return validReadCount;
    }

    /**
     * Sets the value of the validReadCount property.
     * 
     */
    public void setValidReadCount(long value) {
        this.validReadCount = value;
    }

    /**
     * Gets the value of the kmerCountStatsTablePath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKmerCountStatsTablePath() {
        return kmerCountStatsTablePath;
    }

    /**
     * Sets the value of the kmerCountStatsTablePath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKmerCountStatsTablePath(String value) {
        this.kmerCountStatsTablePath = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
