//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.06 at 02:30:00 PM EST 
//


package config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}ExperimentReference"/>
 *         &lt;element ref="{}Filter" minOccurs="0"/>
 *         &lt;element ref="{}CrossValidationSetting" minOccurs="0"/>
 *         &lt;element ref="{}ModelLength"/>
 *         &lt;element ref="{}MarkovModelMethod"/>
 *         &lt;element ref="{}ModelOrder"/>
 *         &lt;element ref="{}TransitionTablePath"/>
 *         &lt;element ref="{}ModelLogPath"/>
 *         &lt;element ref="{}PearsonCoefficient" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "experimentReference",
    "filter",
    "crossValidationSetting",
    "modelLength",
    "markovModelMethod",
    "modelOrder",
    "transitionTablePath",
    "modelLogPath",
    "pearsonCoefficient"
})
@XmlRootElement(name = "MarkovModelStats")
public class MarkovModelStats {

    @XmlElement(name = "ExperimentReference", required = true)
    protected ExperimentReference experimentReference;
    @XmlElement(name = "Filter", defaultValue = "")
    protected String filter;
    @XmlElement(name = "CrossValidationSetting")
    protected CrossValidationSetting crossValidationSetting;
    @XmlElement(name = "ModelLength")
    protected int modelLength;
    @XmlElement(name = "MarkovModelMethod", required = true)
    protected String markovModelMethod;
    @XmlElement(name = "ModelOrder")
    protected int modelOrder;
    @XmlElement(name = "TransitionTablePath", required = true)
    protected String transitionTablePath;
    @XmlElement(name = "ModelLogPath", required = true)
    protected String modelLogPath;
    @XmlElement(name = "PearsonCoefficient")
    protected Double pearsonCoefficient;
    @XmlAttribute(required = true)
    protected String id;

    /**
     * Gets the value of the experimentReference property.
     * 
     * @return
     *     possible object is
     *     {@link ExperimentReference }
     *     
     */
    public ExperimentReference getExperimentReference() {
        return experimentReference;
    }

    /**
     * Sets the value of the experimentReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExperimentReference }
     *     
     */
    public void setExperimentReference(ExperimentReference value) {
        this.experimentReference = value;
    }

    /**
     * Gets the value of the filter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFilter() {
        return filter;
    }

    /**
     * Sets the value of the filter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFilter(String value) {
        this.filter = value;
    }

    /**
     * Gets the value of the crossValidationSetting property.
     * 
     * @return
     *     possible object is
     *     {@link CrossValidationSetting }
     *     
     */
    public CrossValidationSetting getCrossValidationSetting() {
        return crossValidationSetting;
    }

    /**
     * Sets the value of the crossValidationSetting property.
     * 
     * @param value
     *     allowed object is
     *     {@link CrossValidationSetting }
     *     
     */
    public void setCrossValidationSetting(CrossValidationSetting value) {
        this.crossValidationSetting = value;
    }

    /**
     * Gets the value of the modelLength property.
     * 
     */
    public int getModelLength() {
        return modelLength;
    }

    /**
     * Sets the value of the modelLength property.
     * 
     */
    public void setModelLength(int value) {
        this.modelLength = value;
    }

    /**
     * Gets the value of the markovModelMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarkovModelMethod() {
        return markovModelMethod;
    }

    /**
     * Sets the value of the markovModelMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarkovModelMethod(String value) {
        this.markovModelMethod = value;
    }

    /**
     * Gets the value of the modelOrder property.
     * 
     */
    public int getModelOrder() {
        return modelOrder;
    }

    /**
     * Sets the value of the modelOrder property.
     * 
     */
    public void setModelOrder(int value) {
        this.modelOrder = value;
    }

    /**
     * Gets the value of the transitionTablePath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransitionTablePath() {
        return transitionTablePath;
    }

    /**
     * Sets the value of the transitionTablePath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransitionTablePath(String value) {
        this.transitionTablePath = value;
    }

    /**
     * Gets the value of the modelLogPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModelLogPath() {
        return modelLogPath;
    }

    /**
     * Sets the value of the modelLogPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModelLogPath(String value) {
        this.modelLogPath = value;
    }

    /**
     * Gets the value of the pearsonCoefficient property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPearsonCoefficient() {
        return pearsonCoefficient;
    }

    /**
     * Sets the value of the pearsonCoefficient property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPearsonCoefficient(Double value) {
        this.pearsonCoefficient = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
