//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.06 at 02:30:00 PM EST 
//


package config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}DataSource"/>
 *         &lt;element ref="{}CrossValidation"/>
 *         &lt;element ref="{}InformationGain"/>
 *         &lt;element ref="{}Settings"/>
 *       &lt;/sequence>
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" default="markov" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dataSource",
    "crossValidation",
    "informationGain",
    "settings"
})
@XmlRootElement(name = "Model")
public class Model {

    @XmlElement(name = "DataSource", required = true)
    protected DataSource dataSource;
    @XmlElement(name = "CrossValidation", required = true)
    protected CrossValidation crossValidation;
    @XmlElement(name = "InformationGain", required = true)
    protected InformationGain informationGain;
    @XmlElement(name = "Settings", required = true)
    protected Settings settings;
    @XmlAttribute
    protected String type;

    /**
     * Gets the value of the dataSource property.
     * 
     * @return
     *     possible object is
     *     {@link DataSource }
     *     
     */
    public DataSource getDataSource() {
        return dataSource;
    }

    /**
     * Sets the value of the dataSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataSource }
     *     
     */
    public void setDataSource(DataSource value) {
        this.dataSource = value;
    }

    /**
     * Gets the value of the crossValidation property.
     * 
     * @return
     *     possible object is
     *     {@link CrossValidation }
     *     
     */
    public CrossValidation getCrossValidation() {
        return crossValidation;
    }

    /**
     * Sets the value of the crossValidation property.
     * 
     * @param value
     *     allowed object is
     *     {@link CrossValidation }
     *     
     */
    public void setCrossValidation(CrossValidation value) {
        this.crossValidation = value;
    }

    /**
     * Gets the value of the informationGain property.
     * 
     * @return
     *     possible object is
     *     {@link InformationGain }
     *     
     */
    public InformationGain getInformationGain() {
        return informationGain;
    }

    /**
     * Sets the value of the informationGain property.
     * 
     * @param value
     *     allowed object is
     *     {@link InformationGain }
     *     
     */
    public void setInformationGain(InformationGain value) {
        this.informationGain = value;
    }

    /**
     * Gets the value of the settings property.
     * 
     * @return
     *     possible object is
     *     {@link Settings }
     *     
     */
    public Settings getSettings() {
        return settings;
    }

    /**
     * Sets the value of the settings property.
     * 
     * @param value
     *     allowed object is
     *     {@link Settings }
     *     
     */
    public void setSettings(Settings value) {
        this.settings = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        if (type == null) {
            return "markov";
        } else {
            return type;
        }
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

}
