//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.06 at 02:30:00 PM EST 
//


package config;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the config package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DataFile_QNAME = new QName("", "DataFile");
    private final static QName _TotalLineCount_QNAME = new QName("", "TotalLineCount");
    private final static QName _ModelLength_QNAME = new QName("", "ModelLength");
    private final static QName _ModelLogPath_QNAME = new QName("", "ModelLogPath");
    private final static QName _LeftBarcode_QNAME = new QName("", "LeftBarcode");
    private final static QName _ResearcherEmail_QNAME = new QName("", "ResearcherEmail");
    private final static QName _Offset_QNAME = new QName("", "Offset");
    private final static QName _KmerCountStatsTablePath_QNAME = new QName("", "KmerCountStatsTablePath");
    private final static QName _MinimalCount_QNAME = new QName("", "MinimalCount");
    private final static QName _TotalBarcodeMatchedReadCount_QNAME = new QName("", "TotalBarcodeMatchedReadCount");
    private final static QName _LowestCount_QNAME = new QName("", "LowestCount");
    private final static QName _BarcodeOffset_QNAME = new QName("", "BarcodeOffset");
    private final static QName _Kmax_QNAME = new QName("", "Kmax");
    private final static QName _TotalReadCount_QNAME = new QName("", "TotalReadCount");
    private final static QName _VariableRegionLength_QNAME = new QName("", "VariableRegionLength");
    private final static QName _SequencingConfigPath_QNAME = new QName("", "SequencingConfigPath");
    private final static QName _OriginalDataFilePath_QNAME = new QName("", "OriginalDataFilePath");
    private final static QName _ModelOrder_QNAME = new QName("", "ModelOrder");
    private final static QName _InformationGainValue_QNAME = new QName("", "InformationGainValue");
    private final static QName _InformationGainCurrentRound_QNAME = new QName("", "InformationGainCurrentRound");
    private final static QName _Tag_QNAME = new QName("", "Tag");
    private final static QName _SequencingFacilityName_QNAME = new QName("", "SequencingFacilityName");
    private final static QName _ModelID_QNAME = new QName("", "ModelID");
    private final static QName _MarkovModelMethod_QNAME = new QName("", "MarkovModelMethod");
    private final static QName _Protein_QNAME = new QName("", "Protein");
    private final static QName _RightFlank_QNAME = new QName("", "RightFlank");
    private final static QName _RightBarcode_QNAME = new QName("", "RightBarcode");
    private final static QName _Description_QNAME = new QName("", "Description");
    private final static QName _PearsonCoefficient_QNAME = new QName("", "PearsonCoefficient");
    private final static QName _ConfigurationPath_QNAME = new QName("", "ConfigurationPath");
    private final static QName _SequencingFacilityEmail_QNAME = new QName("", "SequencingFacilityEmail");
    private final static QName _Concentration_QNAME = new QName("", "Concentration");
    private final static QName _Notes_QNAME = new QName("", "Notes");
    private final static QName _LeftFlank_QNAME = new QName("", "LeftFlank");
    private final static QName _Filter_QNAME = new QName("", "Filter");
    private final static QName _ValidReadCount_QNAME = new QName("", "ValidReadCount");
    private final static QName _DataFileType_QNAME = new QName("", "DataFileType");
    private final static QName _HighestCount_QNAME = new QName("", "HighestCount");
    private final static QName _Length_QNAME = new QName("", "Length");
    private final static QName _SequencingPlatform_QNAME = new QName("", "SequencingPlatform");
    private final static QName _ResearcherName_QNAME = new QName("", "ResearcherName");
    private final static QName _CachedDataFilePath_QNAME = new QName("", "CachedDataFilePath");
    private final static QName _TransitionTablePath_QNAME = new QName("", "TransitionTablePath");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: config
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SELEXProcessConfig }
     * 
     */
    public SELEXProcessConfig createSELEXProcessConfig() {
        return new SELEXProcessConfig();
    }

    /**
     * Create an instance of {@link InformationGainStats }
     * 
     */
    public InformationGainStats createInformationGainStats() {
        return new InformationGainStats();
    }

    /**
     * Create an instance of {@link AdditionalDataSet }
     * 
     */
    public AdditionalDataSet createAdditionalDataSet() {
        return new AdditionalDataSet();
    }

    /**
     * Create an instance of {@link Round0 }
     * 
     */
    public Round0 createRound0() {
        return new Round0();
    }

    /**
     * Create an instance of {@link Model }
     * 
     */
    public Model createModel() {
        return new Model();
    }

    /**
     * Create an instance of {@link InformationGain }
     * 
     */
    public InformationGain createInformationGain() {
        return new InformationGain();
    }

    /**
     * Create an instance of {@link Settings }
     * 
     */
    public Settings createSettings() {
        return new Settings();
    }

    /**
     * Create an instance of {@link Sample }
     * 
     */
    public Sample createSample() {
        return new Sample();
    }

    /**
     * Create an instance of {@link InputDataSetStats }
     * 
     */
    public InputDataSetStats createInputDataSetStats() {
        return new InputDataSetStats();
    }

    /**
     * Create an instance of {@link CrossValidation }
     * 
     */
    public CrossValidation createCrossValidation() {
        return new CrossValidation();
    }

    /**
     * Create an instance of {@link Process }
     * 
     */
    public Process createProcess() {
        return new Process();
    }

    /**
     * Create an instance of {@link KmerCountStats }
     * 
     */
    public KmerCountStats createKmerCountStats() {
        return new KmerCountStats();
    }

    /**
     * Create an instance of {@link SELEXSequencingConfig }
     * 
     */
    public SELEXSequencingConfig createSELEXSequencingConfig() {
        return new SELEXSequencingConfig();
    }

    /**
     * Create an instance of {@link DataSource }
     * 
     */
    public DataSource createDataSource() {
        return new DataSource();
    }

    /**
     * Create an instance of {@link SequencingRunInfo }
     * 
     */
    public SequencingRunInfo createSequencingRunInfo() {
        return new SequencingRunInfo();
    }

    /**
     * Create an instance of {@link ExperimentReference }
     * 
     */
    public ExperimentReference createExperimentReference() {
        return new ExperimentReference();
    }

    /**
     * Create an instance of {@link MarkovModelStats }
     * 
     */
    public MarkovModelStats createMarkovModelStats() {
        return new MarkovModelStats();
    }

    /**
     * Create an instance of {@link CrossValidationSetting }
     * 
     */
    public CrossValidationSetting createCrossValidationSetting() {
        return new CrossValidationSetting();
    }

    /**
     * Create an instance of {@link SELEXPipeline }
     * 
     */
    public SELEXPipeline createSELEXPipeline() {
        return new SELEXPipeline();
    }

    /**
     * Create an instance of {@link SELEXStats }
     * 
     */
    public SELEXStats createSELEXStats() {
        return new SELEXStats();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DataFile")
    public JAXBElement<String> createDataFile(String value) {
        return new JAXBElement<String>(_DataFile_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TotalLineCount")
    public JAXBElement<Long> createTotalLineCount(Long value) {
        return new JAXBElement<Long>(_TotalLineCount_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ModelLength")
    public JAXBElement<Integer> createModelLength(Integer value) {
        return new JAXBElement<Integer>(_ModelLength_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ModelLogPath")
    public JAXBElement<String> createModelLogPath(String value) {
        return new JAXBElement<String>(_ModelLogPath_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LeftBarcode")
    public JAXBElement<String> createLeftBarcode(String value) {
        return new JAXBElement<String>(_LeftBarcode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ResearcherEmail", defaultValue = "")
    public JAXBElement<String> createResearcherEmail(String value) {
        return new JAXBElement<String>(_ResearcherEmail_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Offset", defaultValue = "-1")
    public JAXBElement<Integer> createOffset(Integer value) {
        return new JAXBElement<Integer>(_Offset_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "KmerCountStatsTablePath")
    public JAXBElement<String> createKmerCountStatsTablePath(String value) {
        return new JAXBElement<String>(_KmerCountStatsTablePath_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MinimalCount")
    public JAXBElement<Integer> createMinimalCount(Integer value) {
        return new JAXBElement<Integer>(_MinimalCount_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TotalBarcodeMatchedReadCount")
    public JAXBElement<Long> createTotalBarcodeMatchedReadCount(Long value) {
        return new JAXBElement<Long>(_TotalBarcodeMatchedReadCount_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LowestCount")
    public JAXBElement<Long> createLowestCount(Long value) {
        return new JAXBElement<Long>(_LowestCount_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BarcodeOffset")
    public JAXBElement<Integer> createBarcodeOffset(Integer value) {
        return new JAXBElement<Integer>(_BarcodeOffset_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Kmax")
    public JAXBElement<Integer> createKmax(Integer value) {
        return new JAXBElement<Integer>(_Kmax_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TotalReadCount")
    public JAXBElement<Long> createTotalReadCount(Long value) {
        return new JAXBElement<Long>(_TotalReadCount_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "VariableRegionLength")
    public JAXBElement<Integer> createVariableRegionLength(Integer value) {
        return new JAXBElement<Integer>(_VariableRegionLength_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SequencingConfigPath")
    public JAXBElement<String> createSequencingConfigPath(String value) {
        return new JAXBElement<String>(_SequencingConfigPath_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OriginalDataFilePath")
    public JAXBElement<String> createOriginalDataFilePath(String value) {
        return new JAXBElement<String>(_OriginalDataFilePath_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ModelOrder")
    public JAXBElement<Integer> createModelOrder(Integer value) {
        return new JAXBElement<Integer>(_ModelOrder_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "InformationGainValue")
    public JAXBElement<Double> createInformationGainValue(Double value) {
        return new JAXBElement<Double>(_InformationGainValue_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "InformationGainCurrentRound")
    public JAXBElement<Integer> createInformationGainCurrentRound(Integer value) {
        return new JAXBElement<Integer>(_InformationGainCurrentRound_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Tag")
    public JAXBElement<String> createTag(String value) {
        return new JAXBElement<String>(_Tag_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SequencingFacilityName", defaultValue = "")
    public JAXBElement<String> createSequencingFacilityName(String value) {
        return new JAXBElement<String>(_SequencingFacilityName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ModelID")
    public JAXBElement<String> createModelID(String value) {
        return new JAXBElement<String>(_ModelID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MarkovModelMethod")
    public JAXBElement<String> createMarkovModelMethod(String value) {
        return new JAXBElement<String>(_MarkovModelMethod_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Protein", defaultValue = "")
    public JAXBElement<String> createProtein(String value) {
        return new JAXBElement<String>(_Protein_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RightFlank")
    public JAXBElement<String> createRightFlank(String value) {
        return new JAXBElement<String>(_RightFlank_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RightBarcode")
    public JAXBElement<String> createRightBarcode(String value) {
        return new JAXBElement<String>(_RightBarcode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Description", defaultValue = "")
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<String>(_Description_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PearsonCoefficient")
    public JAXBElement<Double> createPearsonCoefficient(Double value) {
        return new JAXBElement<Double>(_PearsonCoefficient_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ConfigurationPath")
    public JAXBElement<String> createConfigurationPath(String value) {
        return new JAXBElement<String>(_ConfigurationPath_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SequencingFacilityEmail", defaultValue = "")
    public JAXBElement<String> createSequencingFacilityEmail(String value) {
        return new JAXBElement<String>(_SequencingFacilityEmail_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Concentration", defaultValue = "")
    public JAXBElement<String> createConcentration(String value) {
        return new JAXBElement<String>(_Concentration_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Notes", defaultValue = "")
    public JAXBElement<String> createNotes(String value) {
        return new JAXBElement<String>(_Notes_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LeftFlank")
    public JAXBElement<String> createLeftFlank(String value) {
        return new JAXBElement<String>(_LeftFlank_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Filter", defaultValue = "")
    public JAXBElement<String> createFilter(String value) {
        return new JAXBElement<String>(_Filter_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ValidReadCount")
    public JAXBElement<Long> createValidReadCount(Long value) {
        return new JAXBElement<Long>(_ValidReadCount_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DataFileType", defaultValue = "FASTQ.TXT")
    public JAXBElement<String> createDataFileType(String value) {
        return new JAXBElement<String>(_DataFileType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HighestCount")
    public JAXBElement<Long> createHighestCount(Long value) {
        return new JAXBElement<Long>(_HighestCount_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Length")
    public JAXBElement<Integer> createLength(Integer value) {
        return new JAXBElement<Integer>(_Length_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SequencingPlatform", defaultValue = "")
    public JAXBElement<String> createSequencingPlatform(String value) {
        return new JAXBElement<String>(_SequencingPlatform_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ResearcherName", defaultValue = "")
    public JAXBElement<String> createResearcherName(String value) {
        return new JAXBElement<String>(_ResearcherName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CachedDataFilePath")
    public JAXBElement<String> createCachedDataFilePath(String value) {
        return new JAXBElement<String>(_CachedDataFilePath_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TransitionTablePath")
    public JAXBElement<String> createTransitionTablePath(String value) {
        return new JAXBElement<String>(_TransitionTablePath_QNAME, String.class, null, value);
    }

}
