//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.06 at 02:30:00 PM EST 
//


package config;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="sequencingName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="sampleName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="sampleRound" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "Round0")
public class Round0 {

    @XmlAttribute(required = true)
    protected String sequencingName;
    @XmlAttribute(required = true)
    protected String sampleName;
    @XmlAttribute
    protected BigInteger sampleRound;

    /**
     * Gets the value of the sequencingName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSequencingName() {
        return sequencingName;
    }

    /**
     * Sets the value of the sequencingName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSequencingName(String value) {
        this.sequencingName = value;
    }

    /**
     * Gets the value of the sampleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSampleName() {
        return sampleName;
    }

    /**
     * Sets the value of the sampleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSampleName(String value) {
        this.sampleName = value;
    }

    /**
     * Gets the value of the sampleRound property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSampleRound() {
        return sampleRound;
    }

    /**
     * Sets the value of the sampleRound property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSampleRound(BigInteger value) {
        this.sampleRound = value;
    }

}
